employees/urls.py
from django.urls import path

from . import views
app_name = 'employees'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('register', views.register, name = 'register'),
	#path('login', views.login_view, name = 'login'),
	path('logout', views.logout_view, name= 'logout'),
	path('profile', views.profile, name = 'profile'),
	path('apply', views.apply, name = 'apply'),
	path('manage_requests', views.manage_requests, name = 'manage_requests'),
	path('update_application', views.update_application, name = 'update_application'),
	path('<int:leaverequest_id>/decision', views.decision, name = 'decision'),
]

leave_management/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from employees import views
router = routers.DefaultRouter()
router.register(r'departments',views.DepartmentViewSet)
router.register(r'users',views.UserViewSet)
router.register(r'employee_profiles',views.EmployeeProfileViewSet)
router.register(r'leave_requests',views.LeaveRequestViewSet)
router.register(r'managed_requests',views.ManageRequestViewSet)

urlpatterns = [
	path('employees/', include('employees.urls')),
    path('admin/', admin.site.urls),
    path('',include(router.urls)),
    path('leave_management_api/',include('rest_framework.urls',namespace='rest_framework')),
]

employees/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

status = (('Pending','Pending'),('Approved','Approved'),('Rejected','Rejected'))
leave_types = ((0,'Study'),(1,'Medical'),(2,'Emergency'),(3,'Vacation'),(4,'Other'))

class Department(models.Model):
	department = models.CharField(max_length=100)

	def __str__(self):
		return self.department

class EmployeeProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	department = models.ForeignKey('Department', on_delete=models.CASCADE)
	dob = models.DateField('Date of Birth')
	address = models.CharField(max_length=75)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=50)
	origin_state = models.CharField(max_length=50)
	nationality = models.CharField(max_length=50)
	mobile = models.CharField(max_length=15)

	def __str__(self):
		#return self.user.username
		return '%s %s' % (self.user.first_name, self.user.last_name)
	

class LeaveRequest(models.Model):
	employee = models.OneToOneField(EmployeeProfile, on_delete=models.CASCADE)
	start_date = models.DateField(help_text='Start of Leave')
	end_date = models.DateField(help_text='End of Leave')
	leave_type = models.IntegerField(choices=leave_types, default=0)
	reason_for_leave = models.TextField(max_length=250)
	#time_submitted = models.DateTimeField()
	#time_approved = models.DateTimeField()

	def __str__(self):
		return '%s %s %s' % (self.employee.user.first_name, self.employee.user.last_name,
		self.employee.department)

class ManageRequest(models.Model):
	manage_request = models.OneToOneField(LeaveRequest,on_delete=models.CASCADE)#,null=True)
	status_decision = models.CharField(max_length=20,choices=status)#, default=0)
	#listed=models.BooleanField(default=True)

	def __str__(self):
		return '%s %s' % (self.manage_request.employee.user.first_name, 
		self.manage_request.employee.user.last_name)

employees/forms.py
from django import forms
from .models import EmployeeProfile, Department, LeaveRequest, ManageRequest
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.admin import widgets
from django.forms.widgets import SelectDateWidget

years = [x for x in range(1940, 2050)]

class ExtendedUserCreationForm(UserCreationForm):
	email = forms.EmailField(max_length=100)
	first_name = forms.CharField(max_length=50)
	last_name = forms.CharField(max_length=50)

	def __init__(self, *args, **kwargs):
		super(ExtendedUserCreationForm, self).__init__(*args,**kwargs)

		for fieldname in ['username', 'email', 'password1', 'password2']:
			self.fields[fieldname].help_text = None

	class Meta:
		model = User
		fields = ('username','email','first_name','last_name','password1','password2')

	def save(self, commit=True):
		user = super().save(commit=False)
		user.email = self.cleaned_data['email']
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']

		if commit:
			user.save()
		return user

class EmployeeProfileForm(forms.ModelForm):
	class Meta:
		model = EmployeeProfile
		fields = ('mobile','department','dob','address','city','state','origin_state','nationality')
	def __init__(self, *args, **kwargs):
		super(EmployeeProfileForm, self).__init__(*args, **kwargs)
		self.fields['dob'].widget = SelectDateWidget(years=years)

class LeaveRequestForm(forms.ModelForm):
	class Meta:
		model = LeaveRequest
		fields = ('employee','leave_type','reason_for_leave','start_date', 'end_date')
		
	def __init__(self, *args, **kwargs):
		from django.forms.widgets import HiddenInput, SelectDateWidget
		hide_condition = kwargs.pop('hide_condition',None)
		super(LeaveRequestForm, self).__init__(*args, **kwargs)
		self.fields['start_date'].widget = SelectDateWidget(years=years)
		self.fields['end_date'].widget = SelectDateWidget(years=years)

		if hide_condition:
			self.fields['employee'].widget = HiddenInput()

class ManageRequestForm(forms.ModelForm):
	class Meta:
		model = ManageRequest
		fields = ('manage_request','status_decision')
	
	def __init__(self, *args, **kwargs):
		from django.forms.widgets import HiddenInput
		hide_condition = kwargs.pop('hide_condition',None)
		super(ManageRequestForm, self).__init__(*args, **kwargs)
		if hide_condition:
			self.fields['manage_request'].widget = HiddenInput()

employees/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import EmployeeProfile, LeaveRequest, ManageRequest
from django.contrib.auth.decorators import login_required
from .forms import EmployeeProfileForm, ExtendedUserCreationForm, LeaveRequestForm, ManageRequestForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views import generic
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from rest_framework import viewsets
from .serializers import *

class DepartmentViewSet(viewsets.ModelViewSet):
	queryset = Department.objects.all()
	serializer_class = DepartmentSerializer

class UserViewSet(viewsets.ModelViewSet):
	queryset = User.objects.all()
	serializer_class = UserSerializer

class EmployeeProfileViewSet(viewsets.ModelViewSet):
	queryset = EmployeeProfile.objects.all()
	serializer_class = EmployeeProfileSerializer

class LeaveRequestViewSet(viewsets.ModelViewSet):
	queryset = LeaveRequest.objects.all()
	serializer_class = LeaveRequestSerializer

class ManageRequestViewSet(viewsets.ModelViewSet):
	queryset = ManageRequest.objects.all()
	serializer_class = ManageRequestSerializer

custom_user = None
custom2_user = None

def index(request):
	if not request.user.is_authenticated:
		if request.method == 'POST':
			form = AuthenticationForm(request=request, data=request.POST)
			if form.is_valid():
				username = form.cleaned_data.get('username')
				password = form.cleaned_data.get('password')
				user = authenticate(username=username, password=password)
				if user is not None:
					login(request, user)
					messages.info(request, f"You are now logged in as {username}")
					return HttpResponseRedirect(reverse('employees:index'))
				else:
					messages.error(request, "invalid username or password")
			else:
					messages.error(request, "invalid username or password")
		form = AuthenticationForm()
		return render(request, 'employees/index.html',{'form':form})
	else:
		return render(request, 'employees/index.html')

@login_required
def apply(request):
	
	if request.method == 'POST':
		form = LeaveRequestForm(request.POST,hide_condition=True)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('employees:profile'))
	else:
		default = EmployeeProfile.objects.get(user=request.user)

		form = LeaveRequestForm(initial={'employee':default},hide_condition=True)
	context = {'form':form}
	return render(request, 'employees/apply.html',context)

def register(request):
	if request.method == 'POST':
		form = ExtendedUserCreationForm(request.POST)
		profile_form = EmployeeProfileForm(request.POST)

		if form.is_valid() and profile_form.is_valid():
			user = form.save()
			profile1 = profile_form.save(commit=False)
			profile1.user = user
			profile1.save()
		
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password1')
			user = authenticate(username = username, password = password)
			login(request, user)
			return HttpResponseRedirect(reverse('employees:index'))
	else:
		form = ExtendedUserCreationForm()
		profile_form = EmployeeProfileForm()
	context = {'form':form,'profile_form':profile_form}
	return render(request, 'employees/registration.html',context)

@login_required
def profile(request):
	employee_detail = EmployeeProfile.objects.get(user=request.user.id)
	context = {'employee_detail':employee_detail}
	global custom_user
	custom_user = request.user.id
	return render(request, 'employees/profile.html',context)

@staff_member_required
def manage_requests(request):
	leave_applications = LeaveRequest.objects.all()
	context = {'leave_applications':leave_applications}
	return render(request, 'employees/manage_requests.html', context)

@staff_member_required
def decision(request, leaverequest_id):
	leave_detail = get_object_or_404(LeaveRequest, pk = leaverequest_id)
	global custom2_user
	custom2_user = leaverequest_id

	if request.method == 'POST':
		form = ManageRequestForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('employees:update_application')
			
	else:
		default = LeaveRequest.objects.get(id=leaverequest_id)
		form = ManageRequestForm(initial={'manage_request':default},hide_condition=True)
	context = {'form':form,'leave_detail':leave_detail}
	
	return render(request,'employees/application.html',context=context)


@staff_member_required
def update_application(request):
	leave_request = LeaveRequest.objects.get(id=custom2_user)
	manager_decision = ManageRequest.objects.get(manage_request=leave_request)
	context = {'leave_request':leave_request,'manager_decision':manager_decision}

	if manager_decision.status_decision == 'Approved':
		delete_items = LeaveRequest.objects.filter(id=custom2_user)
		delete_items.delete()

	elif ManageRequest.status_decision == 'Rejected':
		delete_items = LeaveRequest.objects.filter(pk=leaverequest_id)
		delete_items.delete()
	
	return render(request,'employees/approved.html',context=context)
	#return HttpResponseRedirect(reverse('employees:index'))

@login_required
def logout_view(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect('employees:index')

employees/templates/employees/application.html
<!DOCTYPE html>
<html>
<title>Leave Management Sytem</title>

<meta charset="utf-8">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="w3-top">
 <div class="w3-bar w3-theme-d2 w3-left-align">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
  <a href="/employees" class="w3-bar-item w3-button w3-teal"><i class="fa fa-home w3-margin-right"></i>Leave Management</a>
  <a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Process Leave Requests</a>
  <a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Sign Out</a>
 </div>
</div>

<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium">  	
  	<a href="/employees" class="w3-bar-item w3-button">Leave Management</a>
  	<a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button">Process Leave Requests</a>
	<a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button">Sign Out</a>
</div>
</div>

<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third" style="margin-top:3vw;">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-container">
          <div class="w3-container w3-text-black">
            <h2>{{ leave_detail.employee.user.first_name }} {{ leave_detail.employee.user.last_name }}</h2>
          </div>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ leave_detail.employee.department }}</p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ leave_detail.employee.state }}, {{ leave_detail.employee.nationality }}</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ leave_detail.employee.user.email }}</p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ leave_detail.employee.mobile }}</p>
          <hr>

          <br>
        </div>
      </div><br>

    </div>
    <div class="w3-twothird" style="margin-top:3vw;">
    
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Reason for Leave Request</h2>
        <div class="w3-container">
          <h5 class="w3-opacity"><b>Leave Type: {{ leave_detail.get_leave_type_display }}</b></h5>
          <h5 class="w3-opacity"><b>Leave Period: </b></h5><h6 class="w3-text-teal"><h5 class="w3-opacity"><i class="fa fa-calendar fa-fw w3-margin-right"></i>{{ leave_detail.start_date }} - <span>{{ leave_detail.end_date }}</span></h6>
          <h5 class="w3-opacity"><b>Description</b></h5>
          <p>{{ leave_detail.reason_for_leave }}</p>
			<form method="post">
			{% csrf_token %}
			{% for field in form %}
			<div class="grid text-blur">
			  	{{ field.label_tag }}<br>
			  </div>
			  <div class="grid">
			    {{ field }}
			  </div>
			{% if field.help_text %}
			  <small style="color: grey">{{ field.help_text }}</small>
			{% endif %}
			{% for error in field.errors %}
			  <p style="color: red">{{ error }}</p>
			{% endfor %}
			</p>
			{% endfor %}
			<button class="button" style="background-color:#FFD166; color:#000;" type="submit">Update Application</button>
			</form>
          <hr>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "300px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

employees/templates/employees/approved.html
<!DOCTYPE html>
<html>
<title>Leave Management Sytem</title>

<meta charset="utf-8">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="w3-top">
 <div class="w3-bar w3-theme-d2 w3-left-align">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
  <a href="\employees" class="w3-bar-item w3-button w3-teal"><i class="fa fa-home w3-margin-right"></i>Leave Management</a>
  <a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Process Leave Requests</a>
  <a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Sign Out</a>
 </div>
</div>

<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium">  	
  	<a href="\employees" class="w3-bar-item w3-button">Leave Management</a>
  	<a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button">Process Leave Requests</a>
	<a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button">Sign Out</a>
</div>


<div class="w3-container" style="margin-top:5vw;">
	{% if manager_decision.status_decision == 'Approved' %}
		<p> Leave request for <strong>{{ leave_request.employee.user.first_name }} {{ leave_request.employee.user.last_name }}</strong> of the <strong>{{ leave_request.employee.department }}</strong> department has been approved.</p>
	{% elif manager_decision.status_decision == 'Rejected' %}
		<p> Leave request for <strong>{{ leave_request.employee.user.first_name }} {{ leave_request.employee.user.last_name }}</strong> of the <strong>{{ leave_request.employee.department }}</strong> department has been rejected.</p>
	{% endif %}
	<p><a href="/employees/manage_requests">Attend to Other Leave Requests</a></p>
</div>

<script>

function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "300px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
</html>

employees/templates/employees/index.html
<!DOCTYPE html>
<html>
<title>Leave Management Sytem</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body id="myPage">

<div class="w3-top">
 <div class="w3-bar w3-theme-d2 w3-left-align">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>

  <a href="/employees" class="w3-bar-item w3-button w3-teal"><i class="fa fa-home w3-margin-right"></i>Leave Management</a>
  {% if user.is_authenticated and not user.is_superuser %}
  	<a href="{% url 'employees:profile' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Employee Profile</a>
  	<a href="{% url 'employees:apply' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Leave Application</a>
  	<a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Sign Out</a>
  {% elif user.is_authenticated and user.is_superuser %}
  	<a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Process Leave Requests</a>
  	<a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Sign Out</a>
  {% else %}
  	<a href="/employees" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Login</a>
  {% endif %}
 </div>
</div>

<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium">
<a href="/employees" class="w3-bar-item w3-button w3-teal"><i class="fa fa-home w3-margin-right"></i>Leave Management</a>	
{% if user.is_authenticated and not user.is_superuser %}
	<a href="{% url 'employees:profile' %}" class="w3-bar-item w3-button">Employee Profile</a>
	<a href="{% url 'employees:apply' %}" class="w3-bar-item w3-button">Leave Application</a>
	<a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button">Sign Out</a>
{% elif user.is_authenticated and user.is_superuser %}
	<a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button">Process Leave Requests</a>
	<a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button">Sign Out</a>
{% else %}
	<a href="/employees" class="w3-bar-item w3-button">Login</a>
{% endif %}
</div>


<div class="w3-bar-block w3-padding-64 w3-center" id="team">
{% if not user.is_authenticated %}
	<h2>Welcome to the Leave Management System </h2>
	<p>Please proceed to log in or register if you don't have an account:</p>
{% elif user.is_authenticated and user.is_superuser %}
	<h2>Leave Management System </h2>
	<p>Hello Admin, {{ user.last_name }}. <br> Please find pending leave requests awaiting your approval.<br> Thank you. </p>
{% elif user.is_authenticated and not user.is_superuser %}
	<h2>Leave Management System </h2>
	<p>Welcome, Mr. {{ user.last_name }}</p>
	<p>Trust you are having a good day...</p>
{% endif %}
</div>

<div class="w3-container" style="position:relative">
  <a onclick="w3_open()" class="w3-button w3-xlarge w3-circle w3-teal"
  style="position:absolute;top:-28px;right:24px">+</a>
</div>
<div class="w3-bar-block w3-padding-64 w3-center" id="team">
{% if not user.is_authenticated %}
	<div class="w3-row-padding w3-center w3-padding-64" id="pricing">
	    <div class="w3-third w3-margin-bottom">
	      <ul class="w3-ul w3-border w3-hover-shadow">
	      <div class="grid-container">
		      <div class="grid">
		      	<h2>Login</h2>
		      </div>
			  <form method="post">
				{% csrf_token %}
				<div class="grid">
			    	<label class="text-blur">Username:</label>
			    </div>
			    <div class="grid">
			    	<input type="text" class="form-control" placeholder="Username" name="username" value>
			    </div>

			    <div class="grid">
			    	<label class="text-blur">Password:</label>
			    </div>
			    <div class="grid">
			    	<input type="password" class="form-control" placeholder="Password" name="password" value>
			    </div>
			    <div class="grid">		
			    	<button style="background-color:#4CAF50; color:white; box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19); padding: 8px 24px; cursor: pointer;" class="button" type="submit">Login</button>
			    </div>
		  	  </form>
			</div>
	        <li class=" w3-padding-24">
	          <a href="{% url 'employees:register' %}" class="w3-button w3-teal w3-padding-large" "fa fa-check">Register</a>
	          
	        </li>
	      </ul>
	    </div>
	</div>
{% endif %}
</div>


<script>

function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "300px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

employees/templates/employees/manage_requests.html
<!DOCTYPE html>
<html>
<title>Leave Management Sytem</title>

<meta charset="utf-8">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="w3-top">
 <div class="w3-bar w3-theme-d2 w3-left-align">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
  <a href="\employees" class="w3-bar-item w3-button w3-teal"><i class="fa fa-home w3-margin-right"></i>Leave Management</a>
  <a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Process Leave Requests</a>
  <a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Sign Out</a>
 </div>
</div>

<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium">    
    <a href="\employees" class="w3-bar-item w3-button">Leave Management</a>
    <a href="{% url 'employees:manage_requests' %}" class="w3-bar-item w3-button">Process Leave Requests</a>
  <a href="{% url 'employees:logout' %}" class="w3-bar-item w3-button">Sign Out</a>
</div>

<div class="w3-container" style="margin-top:8%; margin-left:1vw">
<h3>Leave Requests Available</h3>	
{% for leave in leave_applications %}
	<a href="{% url 'employees:decision' leave.id %}" class="w3-button" style="padding-left:1px;">{{ leave.employee.user.first_name }} {{ leave.employee.user.last_name }} - {{ leave.employee.department }} </a><br>
{% endfor %}
</div>




<script>

function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "300px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>